### PR TITLE
Set postgres to start on boot.

### PR DESCRIPTION
**Pull request by ghost**
Overview
--------

Brief summary

- use update-rc.d to set postgres to start on boot.

Closes #

Testing
-------

1. Run docker build, see that the rc command runs withhout error.

### CODE REVIEW

**Comment by zeppelin-adazza** [comment]
This change is [Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/16)

**Review by SpainTrain — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/16)* status: 0 of 1 approvals obtained (waiting on @ben-adazza)

___
*[images/finatra-postgres/Dockerfile, line 21 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/16#-LOd3ui63DCwf44rlLqz:-LOd3ui63DCwf44rlLr-:bjw72lu) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/c71a4722ee0794711d07e398a38322b0a695a15a/images/finatra-postgres/Dockerfile#L21)):*
> ```Dockerfile
> USER postgres
> RUN service postgresql start &&\
>     psql --command "CREATE USER adazza WITH SUPERUSER PASSWORD 'adazza';"
> ```

I missed whether the reason for the `&&` (vs 2 lines) was in the previous PR .
___
*[images/finatra-postgres/Dockerfile, line 26 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/16#-LOd3cbW8Lvdd_1xo6_N:-LOd3cbW8Lvdd_1xo6_O:b33ju57) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/c71a4722ee0794711d07e398a38322b0a695a15a/images/finatra-postgres/Dockerfile#L26)):*
> ```Dockerfile
> 
> USER root
> RUN update-rc.d postgresql enable
> ```

Given that these containers spin up, run some commands, then get destroyed, I am not sure I understand this?  Does starting the service not work?  Maybe `service postgresql start` should be run as root.

**Review by SpainTrain — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/16)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ben-adazza)

*[a discussion](https://reviewable.io/reviews/adazza/adazza-ci-docker/16#-LOd4A-k9h7QbEC9qAk1:-LOd4A-k9h7QbEC9qAk2:b-7wd0c) (no related file):*
I am guessing this change is because postgres wasn't running

I am testing some of my questions below so feel free to ignore those for now

---

**Review by ghost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/16)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ben-adazza)

___
*[images/finatra-postgres/Dockerfile, line 21 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/16#-LOd3ui63DCwf44rlLqz:-LOd4xlK1DlQvaX5J9RY:b-yhy8c9) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/c71a4722ee0794711d07e398a38322b0a695a15a/images/finatra-postgres/Dockerfile#L21)):*
<details><summary><i>Previously, SpainTrain (Mike S) wrote…</i></summary><blockquote>

I missed whether the reason for the `&&` (vs 2 lines) was in the previous PR .
</blockquote></details>

Just copy pasta from the internet. Making them two lines is ok with me. 
___
*[images/finatra-postgres/Dockerfile, line 26 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/16#-LOd3cbW8Lvdd_1xo6_N:-LOd4ss8--oFbSG_SeQW:b-kgxusc) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/c71a4722ee0794711d07e398a38322b0a695a15a/images/finatra-postgres/Dockerfile#L26)):*
<details><summary><i>Previously, SpainTrain (Mike S) wrote…</i></summary><blockquote>

Given that these containers spin up, run some commands, then get destroyed, I am not sure I understand this?  Does starting the service not work?  Maybe `service postgresql start` should be run as root.
</blockquote></details>

This is so when the container boots postgres is also started on boot.

**Review by SpainTrain — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/16)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SpainTrain and @ben-adazza)

___
*[images/finatra-postgres/Dockerfile, line 21 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/16#-LOd3ui63DCwf44rlLqz:-LOd93u84z9k4Zt-Yx20:bdgr1a4) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/c71a4722ee0794711d07e398a38322b0a695a15a/images/finatra-postgres/Dockerfile#L21)):*
<details><summary><i>Previously, ben-adazza (Ben McNiel) wrote…</i></summary><blockquote>

Just copy pasta from the internet. Making them two lines is ok with me. 
</blockquote></details>

it was good copy pasta, because it is indeed required :-D

**Review by SpainTrain — DISMISSED** [review]
:shipit: after going back to original revision

> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/16#-:-LOd9c1e4x_zz-1EyHyx:b-sowgjy)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ben-adazza)

*[a discussion](https://reviewable.io/reviews/adazza/adazza-ci-docker/16#-LOd9THa4g6h3BslB2YO:-LOd9THa4g6h3BslB2YP:bimdude) (no related file):*
Sorry for the distracting questions, I should have just done manual testing to understand what was going on.  The original revision is good.

---

**Review by SpainTrain — APPROVED** [review]
:shipit:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/16#-:-LOdn1zL-koJbHLrHcoq:b-xr9eiq)* status: 0 of 1 approvals obtained

**Pull request merged**
