### PR TITLE
feature(add postgres to finatra and scala)

### PR DESCRIPTION
**Pull request by ghost**
Adds 2 new images that add postgres to the finatra and scala
image.

Overview
--------

Brief summary

- Add postgres to scala and finatra images.

Testing
-------

1. cd images/finatra-postgres && docker build .
1. cd images/scala-postgres && docker build .

### CODE REVIEW

**Comment by zeppelin-adazza** [comment]
This change is [Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/15)

**Review by SpainTrain — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/15)* status: 0 of 1 approvals obtained (waiting on @ben-adazza)

___
*[images/finatra-postgres/Dockerfile, line 14 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/15#-LO_3chD355DtU3LGJ1Q:-LO_3chD355DtU3LGJ1R:b-azfcxp) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/d1294ae6e21bdf93bf5e2501798b945cac29f44b/images/finatra-postgres/Dockerfile#L14)):*
> ```Dockerfile
> 
> USER postgres
> RUN /etc/init.d/postgresql start &&\
> ```

does `service start postgresql` not work for this?
___
*[images/finatra-postgres/Dockerfile, line 16 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/15#-LO_4RqHBRY6M-zSLT3n:-LO_4RqHBRY6M-zSLT3o:b-nazsjw) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/d1294ae6e21bdf93bf5e2501798b945cac29f44b/images/finatra-postgres/Dockerfile#L16)):*
> ```Dockerfile
> RUN /etc/init.d/postgresql start &&\
>     psql --command "CREATE USER adazza WITH SUPERUSER PASSWORD 'adazza';"
> RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/10/main/pg_hba.conf
> ```

given that postgres is installed for local testing, is this needed? 
___
*[images/finatra-postgres/Dockerfile, line 21 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/15#-LO_4EQp9fNGxhkYX6Tp:-LO_4EQp9fNGxhkYX6Tq:b-59s08s) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/d1294ae6e21bdf93bf5e2501798b945cac29f44b/images/finatra-postgres/Dockerfile#L21)):*
> ```Dockerfile
> USER root
> 
> EXPOSE 5432
> ```

What is the purpose of exposing this port externally?
___
*[images/finatra-postgres/Dockerfile, line 24 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/15#-LO_3VAn0x6MGN3AmZq4:-LO_3VAn0x6MGN3AmZq5:bs0bcba) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/d1294ae6e21bdf93bf5e2501798b945cac29f44b/images/finatra-postgres/Dockerfile#L24)):*
> ```Dockerfile
> 
> # Install OS deps
> RUN apt-get update
> ```

useless command

If this is intended to be `upgrade`, there are a few things:

- I think I would rather depend on the upstream package-deps base image to take care of this (and we get the updates whenever the base image is updated)
- This is usually an expensive operation, so we probably want it in a higher layer if we do decide we want it at all
- We should probably have a way to "cache bust" the command to force the update to take place, otherwise it will just occur whenever higher layers are updated

Maybe I am missing the intent here?
___
*[images/scala-postgres/Dockerfile, line 1 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/15#-LO_51-KCZhKumBkyhID:-LO_51-KCZhKumBkyhIE:bvvv2rr) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/d1294ae6e21bdf93bf5e2501798b945cac29f44b/images/scala-postgres/Dockerfile#L1)):*
> ```Dockerfile
> FROM buildpack-deps:bionic
> ```

Same comments as other dockerfile

**Review by ghost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/15)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SpainTrain)

___
*[images/finatra-postgres/Dockerfile, line 14 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/15#-LO_3chD355DtU3LGJ1Q:-LO_BiJH8-3V10kli0xr:b-896fix) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/d1294ae6e21bdf93bf5e2501798b945cac29f44b/images/finatra-postgres/Dockerfile#L14)):*
<details><summary><i>Previously, SpainTrain (Mike S) wrote…</i></summary><blockquote>

does `service start postgresql` not work for this?
</blockquote></details>

Done.
___
*[images/finatra-postgres/Dockerfile, line 16 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/15#-LO_4RqHBRY6M-zSLT3n:-LO_Bhx67AQopGBwPO6g:b-896fix) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/d1294ae6e21bdf93bf5e2501798b945cac29f44b/images/finatra-postgres/Dockerfile#L16)):*
<details><summary><i>Previously, SpainTrain (Mike S) wrote…</i></summary><blockquote>

given that postgres is installed for local testing, is this needed? 
</blockquote></details>

Done.
___
*[images/finatra-postgres/Dockerfile, line 21 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/15#-LO_4EQp9fNGxhkYX6Tp:-LO_Bhmg0sMeegfY4RNv:b-896fix) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/d1294ae6e21bdf93bf5e2501798b945cac29f44b/images/finatra-postgres/Dockerfile#L21)):*
<details><summary><i>Previously, SpainTrain (Mike S) wrote…</i></summary><blockquote>

What is the purpose of exposing this port externally?
</blockquote></details>

Done.
___
*[images/finatra-postgres/Dockerfile, line 24 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/15#-LO_3VAn0x6MGN3AmZq4:-LO_BhRE5ERb9aSQUnyl:b-896fix) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/d1294ae6e21bdf93bf5e2501798b945cac29f44b/images/finatra-postgres/Dockerfile#L24)):*
<details><summary><i>Previously, SpainTrain (Mike S) wrote…</i></summary><blockquote>

useless command

If this is intended to be `upgrade`, there are a few things:

- I think I would rather depend on the upstream package-deps base image to take care of this (and we get the updates whenever the base image is updated)
- This is usually an expensive operation, so we probably want it in a higher layer if we do decide we want it at all
- We should probably have a way to "cache bust" the command to force the update to take place, otherwise it will just occur whenever higher layers are updated

Maybe I am missing the intent here?
</blockquote></details>

Done.
___
*[images/scala-postgres/Dockerfile, line 1 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/15#-LO_51-KCZhKumBkyhID:-LO_BgIa7xZAcXfBNX7M:b-896fix) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/d1294ae6e21bdf93bf5e2501798b945cac29f44b/images/scala-postgres/Dockerfile#L1)):*
<details><summary><i>Previously, SpainTrain (Mike S) wrote…</i></summary><blockquote>

Same comments as other dockerfile
</blockquote></details>

Done.

**Review by SpainTrain — APPROVED** [review]
:shipit:

> Reviewed 3 of 4 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/15#-:-LO_Fu733X1L7bHjtbF6:b-xr9eiq)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ben-adazza)

___
*[images/finatra-postgres/Dockerfile, line 20 at r2](https://reviewable.io/reviews/adazza/adazza-ci-docker/15#-LO_FTYN45Q-Xd1tEG7O:-LO_FTYN45Q-Xd1tEG7P:bkmvcjg) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/44d1c077d93d3327760d7b85154ac2d90b4f094a/images/finatra-postgres/Dockerfile#L20)):*
> ```Dockerfile
> 
> USER postgres
> RUN service postgresql start &&\
> ```

nit does this need to be one line with `&&`?

**Pull request merged**
