### PR TITLE
feat(cdk-apps): Add postgres + java [DATA-1342]

### PR DESCRIPTION
**Pull request by ghost**
Overview
--------

Add postgres and java to cdk image.

### CODE REVIEW

**Comment by zeppelin-adazza** [comment]
This change is [Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/95)

**Review by SpainTrain — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/95)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @ben-adazza and @SpainTrain)

___
*[images/cdk-apps/Dockerfile, line 25 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/95#-LapVA5z34mXwJtUdD2L:-LapVA5z34mXwJtUdD2M:bj3z4um) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/b24e779e625310ef77548aced209f8d775e1aca9/images/cdk-apps/Dockerfile#L25)):*
> ```Dockerfile
> 
> # Versioned deps
> RUN npm i -g npm@'~6.9.0' yarn@'1.13.0' n@'2.1.12'
> ```

I'd keep these two lines as close to the bottom as possible since they churn the most
___
*[images/cdk-apps/Dockerfile, line 28 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/95#-LapUtTf1vLImp-0IPDJ:-LapUtTg2XoVGSf8tx1P:b-n61fzi) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/b24e779e625310ef77548aced209f8d775e1aca9/images/cdk-apps/Dockerfile#L28)):*
> ```Dockerfile
> RUN n 10.15.3
> 
> RUN apt-get install -y openjdk-8-jdk
> ```

why do these after installing all the node stuff?  These version should churn much less than npm, yarn, and node, but putting them after means their layer will rebuild every time those things change.

**Review by ghost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/95)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SpainTrain)

___
*[images/cdk-apps/Dockerfile, line 25 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/95#-LapVA5z34mXwJtUdD2L:-LapWXMD2lGDC5Md-jf3:b-896fix) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/b24e779e625310ef77548aced209f8d775e1aca9/images/cdk-apps/Dockerfile#L25)):*
<details><summary><i>Previously, SpainTrain (Mike S) wrote…</i></summary><blockquote>

I'd keep these two lines as close to the bottom as possible since they churn the most
</blockquote></details>

Done.
___
*[images/cdk-apps/Dockerfile, line 28 at r1](https://reviewable.io/reviews/adazza/adazza-ci-docker/95#-LapUtTf1vLImp-0IPDJ:-LapWXfn77BC_6F5V6Du:b-896fix) ([raw file](https://github.com/adazza/adazza-ci-docker/blob/b24e779e625310ef77548aced209f8d775e1aca9/images/cdk-apps/Dockerfile#L28)):*
<details><summary><i>Previously, SpainTrain (Mike S) wrote…</i></summary><blockquote>

why do these after installing all the node stuff?  These version should churn much less than npm, yarn, and node, but putting them after means their layer will rebuild every time those things change.
</blockquote></details>

Done.

**Review by SpainTrain — APPROVED** [review]
:shipit:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/95#-:-LapWmYC3B7ZHD4NpQrn:b-xr9eiq)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
