### PR TITLE
feat(frontend-web): Assert node/npm/yarn versions

### PR DESCRIPTION
**Pull request by SpainTrain**
- This also allows us to bump the version of
  node/npm/yarn in the image by updating the assertion

### CODE REVIEW

**Comment by zeppelin-adazza** [comment]
This change is [Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/8)

**Comment by SpainTrain** [comment]
*[a discussion](https://reviewable.io/reviews/adazza/adazza-ci-docker/8#-LNGZAUn3FNglNtksCkj:-LNGZAUn3FNglNtksCkk:b-coxwek) (no related file):*
FYI needed to fix this build https://console.aws.amazon.com/codebuild/home?region=us-east-1#/builds/adazza-central-web-test-and-build:51daaeaa-729f-47f5-936b-6eb35efec19d/view/new

---

**Review by SpainTrain — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/8)* status: 0 of 1 approvals obtained (waiting on @ben-adazza)

*[a discussion](https://reviewable.io/reviews/adazza/adazza-ci-docker/8#-LNGZAUn3FNglNtksCkj:-LNGZN4p9OukSt565Hrl:b-dkkjbz) (no related file):*
<details><summary><i>Previously, SpainTrain (Mike S) wrote…</i></summary><blockquote>

FYI needed to fix this build https://console.aws.amazon.com/codebuild/home?region=us-east-1#/builds/adazza-central-web-test-and-build:51daaeaa-729f-47f5-936b-6eb35efec19d/view/new
</blockquote></details>

DERP, not that one, this one https://us-east-1.console.aws.amazon.com/codebuild/home?region=us-east-1#/builds/adazza-central-web-pr:920f8c5e-ecf0-494e-b704-cb7908dd23e4/view/new

for https://github.com/Adazza/adazza-central-web/pull/2/

---

**Review by ghost — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/8)* status: 0 of 1 approvals obtained (waiting on @ben-adazza)

**Review by SpainTrain — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/8)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ben-adazza)

*[a discussion](https://reviewable.io/reviews/adazza/adazza-ci-docker/8#-LNGeloaA0AFzVhUNsDQ:-LNGeloaA0AFzVhUNsDR:b-nilxq7) (no related file):*
+@ben-adazza 

---

**Pull request merged**
