### PR TITLE
feat(github): Templates for issues and PRs

### PR DESCRIPTION
**Pull request by SpainTrain**
Overview
--------

Templates for github issues and PRs

Testing
-------

N/A

### CODE REVIEW

**Comment by zeppelin-adazza** [comment]
This change is [Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/10)

**Review by SpainTrain — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/10)* status: 0 of 1 approvals obtained

*[a discussion](https://reviewable.io/reviews/adazza/adazza-ci-docker/10#-LNHoMRSExYIeKcaC5s4:-LNHoMRT7WFHVuZRPpzt:bd9l0hi) (no related file):*
This is just an initial proposal that I am happy to change however makes sense.

---

**Review by ghost — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/10)* status: 0 of 1 approvals obtained (waiting on @ben-adazza)

**Review by ghost — APPROVED** [review]
:shipit:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/adazza/adazza-ci-docker/10#-:-LNMZY6o6OcNABLWojtk:b-xr9eiq)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
